### ISSUE TITLE
Problem including heartland-nodejs in parse-server cloud code

### ISSUE THREAD

**Issue by thailey01** [hps/heartland-nodejs#20]
Hello,

I have been working on adding heartland-nodejs to my parse-server app. I'm trying to make payments in my parse-server cloud code but when I require('heartland-nodejs') my server fails with:
`node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
`

**Comment by slogsdon** [comment]
Hi @thailey01. Thanks for the report!

From the error message, it looks to be related to `node-expat`'s build process. Is your environment caching the `node_modules` directory? Has your environment recently changed/updated the installed version of the Node.JS runtime?

**Comment by thailey01** [comment]
Ok, I got it working by installing node devDependencies electron-prebuilt, electron-rebuild, node-gyp
