### ISSUE TITLE
Ability to set TxnDescriptor?

### ISSUE THREAD

**Issue by charlie-s** [hps/heartland-nodejs#23]
We'd like to set a custom transaction descriptor (`TxnDescriptor`, not the "memo") for our transactions so that we have some control over how charges appear on customer's statements. It appears that this value is the TxnDescriptor, but the node.js library doesn't support a method of setting this. Am I incorrect in my initial assumption? In either event, do you have a recommended method for setting this?

**Comment by slogsdon** [comment]
@charlie-s We don't currently have the TxnDescriptor field exposed via this SDK to pass a dynamic descriptor for a transaction, so it would require a code change (either directly or via fork) to the SDK itself. We don't currently have this work on our backlog, but we would be open to any PRs to add this capability.

While not ideal, there are two additional paths to pass a dynamic descriptor:

1. Integrate directly to the gateway to pass this information
2. Integrate with [our newer SDK](https://www.npmjs.com/package/globalpayments-api) that connects to our Portico gateway as well as the Global Payments eCommerce gateway.

Option 2 above would look like this to complete an authorization request with a dynamic descriptor:

```javascript
const {
  CreditCardData,
  ServicesConfig,
  ServicesContainer,
} = require("globalpayments-api");

const config = new ServicesConfig();
config.secretApiKey = "skapi_cert_MTyMAQBiHVEAewvIzXVFcmUd2UcyBge_eCpaASUp0A";
config.serviceUrl = "https://cert.api2-c.heartlandportico.com";
ServicesContainer.configure(config);

const card = new CreditCardData();
card.token = ""; // token value

card
  .charge(10.00)
  .withCurrency("USD")
  .withDynamicDescriptor("YOUR DESCRIPTOR")
  .execute()
  .then((response) => {
    const result = response.responseCode;
    const message = response.responseMessage;
  })
  .catch((e) => {
    // handle  errors
  });
```

**Comment by charlie-s** [comment]
Happy to try out the new SDK. I didn't realize it existed, actually. I'll check that out and file any issues in the appropriate repo.

**Comment by charlie-s** [comment]
I'm a little confused with the new SDK. The [v3 docs](https://developer.heartlandpaymentsystems.com/Documentation) all seem to link to the hps/nodejs SDK and use that repo's examples, but if you click on "Go to SDK Reference" from the main doc page and then "Node.js", you're taken to the [Global Payments SDK](https://developer.heartlandpaymentsystems.com/Documentation/reference/node-js/) library. Are the v3 docs being slowly migrated, or am I missing something? Should we be using the new Global Payments SDK for all SecureSubmit transactions going forward?

**Comment by slogsdon** [comment]
@charlie-s I believe you're correct there. You should be able to reach out to SecureSubmitCert@e-hps.com to get that sorted.
