### ISSUE TITLE
Add to NPM?

### ISSUE THREAD

**Issue by charlie-s** [hps/heartland-nodejs#6]
Is it likely that this will get added to the NPM registry @ npmjs.org?

**Comment by securesubmit-buildmaster** [comment]
Hi Charlie,

That is the idea! Once we’ve put the touches on it to bring it into parity with our other SDKs then the idea is to add it to the most prevalent package manager for Node.

I currently have no ETA on this effort.

Thanks,

Russell Everett
Senior Developer
russell.everett@e-hps.com<mailto:russell.everett@e-hps.com>
Heartland Payment Systems
One Heartland Way
Jeffersonville, IN 47130
P 812.280.8222 x6562
heartland.us<http://heartland.us/>

**Comment by brahmos** [comment]
Hi Russell, Any ETA on npm availability? We are integrating heartland it would be great if you guys can make it available in npm.

**Comment by slogsdon** [comment]
@charlie-s @brahmos Sorry for the delay. We have deployed the SDK to npm under the package name [`heartland-sdk`](https://www.npmjs.com/package/heartland-nodejs).
